name: Publish PDF
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2.6.0
        with:
          root_file: paper.tex
          latexmk_shell_escape: true
      - name: Upload PDF
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Master Thesis"
          files: |
            paper.pdf
